# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('slack_integration', '0001_initial'), ('slack_integration', '0002_auto_20161129_0145'), ('slack_integration', '0003_auto_20161129_0149'), ('slack_integration', '0004_auto_20161128_1754')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
