# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0001_squashed_0004_auto_20161128_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='datetime',
            new_name='brew_date',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
