# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20161129_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='brew_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
